In [ ]:
import pandas as pd
import numpy as np

In [ ]:
series = pd.Series([7, 4, 2, np.nan, 6, 9])

In [ ]:
series

0    7.0
1    4.0
2    2.0
3    NaN
4    6.0
5    9.0
dtype: float64

In [ ]:
type (series)

pandas.core.series.Series

In [ ]:
datas = pd.date_range('20240101', periods=6)

In [ ]:
datas

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
#help(pd.date_range)

In [ ]:
type(datas)

pandas.core.indexes.datetimes.DatetimeIndex

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index = datas, columns = list("ABCD"))

In [ ]:
np.random.randn(6,4)

array([[-1.18772812, -1.38729096,  0.45748595, -1.2089558 ],
       [-1.23046486,  1.81653437, -0.42769644,  0.34468536],
       [-0.22477844,  1.08817725, -0.53232896, -0.67345488],
       [ 1.01236058,  0.31737544,  0.0792842 , -0.65987192],
       [ 1.11623079,  2.00430193,  0.1862991 ,  0.43598589],
       [-1.71404157,  0.69090563, -0.17098995,  0.51416289]])

In [ ]:
list("ABCD")

['A', 'B', 'C', 'D']

In [ ]:
df

A         B         C         D
2024-01-01 -0.929055 -0.575720  1.578126  1.405887
2024-01-02  1.021749  1.101645 -0.651459 -0.897663
2024-01-03 -0.915105  0.374126  1.032012 -0.768368
2024-01-04  0.004367  0.587388  0.106513  0.378956
2024-01-05 -0.668568 -0.146953 -1.652305  1.527835
2024-01-06  2.058411 -1.227389  3.246633 -0.438145

from matplotlib import pyplot as plt
_df_0['A'].plot(kind='hist', bins=20, title='A')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['B'].plot(kind='hist', bins=20, title='B')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['C'].plot(kind='hist', bins=20, title='C')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['D'].plot(kind='hist', bins=20, title='D')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='A', y='B', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='B', y='C', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='C', y='D', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['A']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('A')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['B']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('B')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['C']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('C')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['D']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('D')

from matplotlib import pyplot as plt
_df_11['A'].plot(kind='line', figsize=(8, 4), title='A')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['B'].plot(kind='line', figsize=(8, 4), title='B')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['C'].plot(kind='line', figsize=(8, 4), title='C')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['D'].plot(kind='line', figsize=(8, 4), title='D')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df2 = pd.DataFrame(np.random.randn(6, 4), index = datas, columns = ['Carros', 'Paises', 'Pessoas', 'Python'])

In [ ]:
df2

Carros    Paises   Pessoas    Python
2024-01-01  0.607926 -0.911765 -1.400049  0.069058
2024-01-02 -0.030624  0.834765  0.589692  0.230797
2024-01-03  0.719997  0.301361  0.533779  0.106785
2024-01-04 -0.864659 -1.176878 -1.491613 -1.173737
2024-01-05  0.753484 -0.731183 -1.421387 -0.189814
2024-01-06  2.896481 -0.093438 -0.143554  0.061870

In [ ]:
df

A         B         C         D
2024-01-01 -0.929055 -0.575720  1.578126  1.405887
2024-01-02  1.021749  1.101645 -0.651459 -0.897663
2024-01-03 -0.915105  0.374126  1.032012 -0.768368
2024-01-04  0.004367  0.587388  0.106513  0.378956
2024-01-05 -0.668568 -0.146953 -1.652305  1.527835
2024-01-06  2.058411 -1.227389  3.246633 -0.438145

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df3 = pd.DataFrame({"A":7,
                    'B': pd.Timestamp('20190101'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    "D": np.array([3]*4, dtype='int32'),
                    "E": pd.Categorical(["teste", "train", "test", "train"]),
                    'F': 'Python'})

In [ ]:
df3

A          B    C  D      E       F
0  7 2019-01-01  1.0  3  teste  Python
1  7 2019-01-01  1.0  3  train  Python
2  7 2019-01-01  1.0  3   test  Python
3  7 2019-01-01  1.0  3  train  Python

In [ ]:
df3.dtypes #para saber o tipo de dados do dataframe

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [34]:
# Visualizar dados

In [35]:
df.head(2) #para vizualizar as duas primeiras linhas

A         B         C         D
2024-01-01 -0.929055 -0.575720  1.578126  1.405887
2024-01-02  1.021749  1.101645 -0.651459 -0.897663

In [38]:
df.tail(3) #para ver as duas ultimas linhas

A         B         C         D
2024-01-04  0.004367  0.587388  0.106513  0.378956
2024-01-05 -0.668568 -0.146953 -1.652305  1.527835
2024-01-06  2.058411 -1.227389  3.246633 -0.438145

In [41]:
df.index #para retornar os indices do dataframe

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06'],
              dtype='datetime64[ns]', freq='D')

In [40]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [42]:
c = df.columns

In [45]:
c

Index(['A', 'B', 'C', 'D'], dtype='object')

In [43]:
df

A         B         C         D
2024-01-01 -0.929055 -0.575720  1.578126  1.405887
2024-01-02  1.021749  1.101645 -0.651459 -0.897663
2024-01-03 -0.915105  0.374126  1.032012 -0.768368
2024-01-04  0.004367  0.587388  0.106513  0.378956
2024-01-05 -0.668568 -0.146953 -1.652305  1.527835
2024-01-06  2.058411 -1.227389  3.246633 -0.438145

In [46]:
df.to_numpy() #transformu todos os dados em uma matriz, obtem somente os dados numericos esquecendo as linhas e conlunas.

array([[-0.92905474, -0.57571998,  1.57812591,  1.40588674],
       [ 1.02174857,  1.10164544, -0.65145857, -0.89766349],
       [-0.91510527,  0.37412639,  1.03201193, -0.76836837],
       [ 0.00436671,  0.58738789,  0.10651348,  0.37895608],
       [-0.66856807, -0.14695325, -1.65230546,  1.5278349 ],
       [ 2.05841082, -1.22738937,  3.24663327, -0.43814511]])

In [48]:
df.T # para obter a transposta do dataframe, transforma linhas em colunas / colunas em linhas

2024-01-01  2024-01-02  2024-01-03  2024-01-04  2024-01-05  2024-01-06
A   -0.929055    1.021749   -0.915105    0.004367   -0.668568    2.058411
B   -0.575720    1.101645    0.374126    0.587388   -0.146953   -1.227389
C    1.578126   -0.651459    1.032012    0.106513   -1.652305    3.246633
D    1.405887   -0.897663   -0.768368    0.378956    1.527835   -0.438145

In [49]:
df2.T

2024-01-01  2024-01-02  2024-01-03  2024-01-04  2024-01-05  \
Carros     0.607926   -0.030624    0.719997   -0.864659    0.753484   
Paises    -0.911765    0.834765    0.301361   -1.176878   -0.731183   
Pessoas   -1.400049    0.589692    0.533779   -1.491613   -1.421387   
Python     0.069058    0.230797    0.106785   -1.173737   -0.189814   

         2024-01-06  
Carros     2.896481  
Paises    -0.093438  
Pessoas   -0.143554  
Python     0.061870

In [50]:
df2.to_numpy()

array([[ 0.60792624, -0.91176502, -1.40004898,  0.06905839],
       [-0.03062396,  0.83476453,  0.58969245,  0.2307966 ],
       [ 0.71999717,  0.30136109,  0.53377854,  0.10678502],
       [-0.864659  , -1.17687786, -1.49161297, -1.17373698],
       [ 0.75348423, -0.73118308, -1.42138657, -0.1898137 ],
       [ 2.89648103, -0.09343843, -0.14355352,  0.06187022]])